// bun scripts/setup.ts — link the runtime this product builds against.
//
// The guest is bundled by the vendored toolchain but resolved from THIS
// repository: an import of "solid-js" or "@pocketjs/framework/components" in
// app/ walks up to ./node_modules, not into the submodule. So the packages
// vendor/pocketjs already installed are linked here rather than installed a
// second time, which also guarantees one copy of Solid.

import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { ROOT, VENDOR } from "./paths.ts";

if (!existsSync(resolve(VENDOR, "package.json"))) {
  throw new Error("Pocket Vault setup: initialize vendor/pocketjs first (git submodule update --init)");
}

const links = new Map<string, string>([
  ["node_modules/@pocketjs/framework", "vendor/pocketjs"],
  ["node_modules/solid-js", "vendor/pocketjs/node_modules/solid-js"],
  ["node_modules/opentype.js", "vendor/pocketjs/node_modules/opentype.js"],
  ["node_modules/@types/opentype.js", "vendor/pocketjs/node_modules/@types/opentype.js"],
  ["node_modules/bun-types", "vendor/pocketjs/node_modules/bun-types"],
  ["node_modules/typescript", "vendor/pocketjs/node_modules/typescript"],
]);

for (const [destination, source] of links) {
  const target = resolve(ROOT, source);
  if (!existsSync(target)) {
    throw new Error(`Pocket Vault setup: missing ${source}; run bun install in vendor/pocketjs`);
  }
  const link = resolve(ROOT, destination);
  mkdirSync(dirname(link), { recursive: true });
  rmSync(link, { recursive: true, force: true });
  symlinkSync(relative(dirname(link), target), link, "dir");
}

// A PocketJS build writes the style table the framework imports; a clean
// submodule has none, and an empty table is the honest state before the
// first build.
const styles = resolve(VENDOR, "framework/src/styles.generated.ts");
if (!existsSync(styles)) {
  writeFileSync(styles, "// Generated by PocketJS builds.\nexport const STYLE_IDS: Record<string, number> = {};\n");
}

console.log("Pocket Vault setup: runtime links ready");
